### ISSUE TITLE
Using the derive macro again

### ISSUE THREAD

**Issue by gabdube** [jcdavis/hroverlay#2]
Hey, I'm the native-windows-gui dev. First, thank you for your article. I think you're the reason why I got close to 100 new stars on the project this week :) 

I just released native-windows-gui 1.0.8 which gives you the ability to specify the extended window flags in the builder API. That means you can now use the derive macro again in your project. 

I have rewritten your UI code. I also replaced the timer with a `Notice` object, which gives you the ability to wake-up the gui thread from another thread and I moved the bt updater creation into the `OnInit` callback . Tell me what you think. I'll do a PR if it's ok.

https://github.com/gabdube/hroverlay/blob/main/src/main.rs

**Comment by jcdavis** [comment]
Thanks for the crate too!

Change looks fine, feel free to create a PR and I'll have look
